version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: voyager/weather-api
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env.example:/var/www/.env
      - ./docker-services/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /var/www/vendor/
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "4001:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-services/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4003:3306"
    environment:
      MYSQL_DATABASE: voyager-weather-api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql:/var/lib/mysql/
      - ./docker-services/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local